In [1]:
import pandas as pd

In [2]:
file = pd.read_csv("noticiasUnificado.csv")
file

C:\Users\samcu\AppData\Local\Temp\ipykernel_12172\3345736279.py:1: DtypeWarning: Columns (2,3,4,5,6,7,8,10,11,12,13,14,15,16,17,18) have mixed types. Specify dtype option on import or set low_memory=False.
  file = pd.read_csv("noticiasUnificado.csv")

,Unnamed: 0,title,publication,author,date,year,month,url,content,id,source_id,source_name,description,url_to_image,published_at,top_article,pubDate,guid,link
0,0.0,House Republicans Fret About Winning Their Hea...,New York Times,Carl Hulse,2016-12-31,2016.0,12.0,Sin url,WASHINGTON — Congressional Republicans have...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,Rift Between Officers and Residents as Killing...,New York Times,Benjamin Mueller and Al Baker,2017-06-19,2017.0,6.0,Sin url,"After the bullet shells get counted, the blood...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.0,"Tyrus Wong, ‘Bambi’ Artist Thwarted by Racial ...",New York Times,Margalit Fox,2017-01-06,2017.0,1.0,Sin url,"When Walt Disney’s “Bambi” opened in 1942, cri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3.0,"Among Deaths in 2016, a Heavy Toll in Pop Musi...",New York Times,William McDonald,2017-04-10,2017.0,4.0,Sin url,"Death may be the great equalizer, but it isn’t...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.0,Kim Jong-un Says North Korea Is Preparing to T...,New York Times,Choe Sang-Hun,2017-01-02,2017.0,1.0,Sin url,"SEOUL, South Korea — North Korea’s leader, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182758,NaN,Ratcliffe wants 'national stadium in north',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New Manchester United co-owner Sir Jim Ratclif...,NaN,NaN,NaN,"Wed, 21 Feb 2024 18:01:39 GMT",https://www.bbc.co.uk/sport/football/68361025,https://www.bbc.co.uk/sport/football/68361025
182759,NaN,Stokes bowls in nets before fourth Test,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,England captain Ben Stokes could bowl in the f...,NaN,NaN,NaN,"Wed, 21 Feb 2024 10:56:13 GMT",https://www.bbc.co.uk/sport/av/cricket/68358578,https://www.bbc.co.uk/sport/av/cricket/68358578
182760,NaN,Gauff 'fuelled' by umpire row to reach Dubai q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,US Open champion Coco Gauff says a long disagr...,NaN,NaN,NaN,"Wed, 21 Feb 2024 19:54:21 GMT",https://www.bbc.co.uk/sport/tennis/68365096,https://www.bbc.co.uk/sport/tennis/68365096
182761,NaN,Verstappen makes ominous start to pre-season t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Red Bull's Max Verstappen makes an ominous sta...,NaN,NaN,NaN,"Wed, 21 Feb 2024 16:51:47 GMT",https://www.bbc.co.uk/sport/formula1/68362786,https://www.bbc.co.uk/sport/formula1/68362786
182762,NaN,Osimhen scores on return as Napoli hold Barcelona,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Victor Osimhen scores in his first Napoli matc...,NaN,NaN,NaN,"Wed, 21 Feb 2024 22:03:23 GMT",https://www.bbc.co.uk/sport/football/68348509,https://www.bbc.co.uk/sport/football/68348509

In [3]:
file.isnull().sum()

Unnamed: 0       29756
title                0
publication      40193
author           29756
date             40193
year             40193
month            40193
url              29756
content          29756
id               90193
source_id       172326
source_name     172326
description     142570
url_to_image    172326
published_at    172326
top_article     172326
pubDate         153007
guid            153007
link            153007
dtype: int64

In [6]:
file.drop('url', axis=1, inplace=True)

In [7]:
file.isnull().sum()

Unnamed: 0       29756
title                0
publication      40193
author           29756
date             40193
year             40193
month            40193
content          29756
id               90193
source_id       172326
source_name     172326
description     142570
url_to_image    172326
published_at    172326
top_article     172326
pubDate         153007
guid            153007
link            153007
dtype: int64

In [9]:
file.drop('guid', axis=1, inplace=True)
file.drop('link', axis=1, inplace=True)
file.drop('source_id', axis=1, inplace=True)
file.drop('source_name', axis=1, inplace=True)
file.drop('description', axis=1, inplace=True)
file.drop('url_to_image', axis=1, inplace=True)
file.drop('published_at', axis=1, inplace=True)
file.drop('top_article', axis=1, inplace=True)
file.drop('pubDate', axis=1, inplace=True)

,Unnamed: 0,title,publication,author,date,year,month,content,id
182263,NaN,Crime to buses: Wellingborough by-election in ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182264,NaN,"Wegovy, the 'Viagra' of weight-loss drugs flyi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
182265,NaN,Trump on Nato: Dangerous talk at a dangerous time,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182266,NaN,Death and Israel’s search for ‘total victory’ ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182267,NaN,"We couldn't afford to bury our baby, says form...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
182758,NaN,Ratcliffe wants 'national stadium in north',NaN,NaN,NaN,NaN,NaN,NaN,NaN
182759,NaN,Stokes bowls in nets before fourth Test,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182760,NaN,Gauff 'fuelled' by umpire row to reach Dubai q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182761,NaN,Verstappen makes ominous start to pre-season t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182762,NaN,Osimhen scores on return as Napoli hold Barcelona,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
file.isnull().sum()

Unnamed: 0     29756
title              0
publication    40193
author         29756
date           40193
year           40193
month          40193
content        29756
id             90193
dtype: int64

In [13]:
file.drop('id', axis=1, inplace=True)

In [14]:
file.isnull().sum()

Unnamed: 0     29756
title              0
publication    40193
author         29756
date           40193
year           40193
month          40193
content        29756
dtype: int64

In [15]:
file.to_csv('newsJoin.csv', index=False)