In [7]:
import pandas as pd

In [8]:
file1 = pd.read_csv("articles1.csv", index_col="id")
file1

,Unnamed: 0,title,publication,author,date,year,month,url,content
id,,,,,,,,,
17283,0,House Republicans Fret About Winning Their Hea...,New York Times,Carl Hulse,2016-12-31,2016.0,12.0,NaN,WASHINGTON — Congressional Republicans have...
17284,1,Rift Between Officers and Residents as Killing...,New York Times,Benjamin Mueller and Al Baker,2017-06-19,2017.0,6.0,NaN,"After the bullet shells get counted, the blood..."
17285,2,"Tyrus Wong, ‘Bambi’ Artist Thwarted by Racial ...",New York Times,Margalit Fox,2017-01-06,2017.0,1.0,NaN,"When Walt Disney’s “Bambi” opened in 1942, cri..."
17286,3,"Among Deaths in 2016, a Heavy Toll in Pop Musi...",New York Times,William McDonald,2017-04-10,2017.0,4.0,NaN,"Death may be the great equalizer, but it isn’t..."
17287,4,Kim Jong-un Says North Korea Is Preparing to T...,New York Times,Choe Sang-Hun,2017-01-02,2017.0,1.0,NaN,"SEOUL, South Korea — North Korea’s leader, ..."
...,...,...,...,...,...,...,...,...,...
73465,53287,"Rex Tillerson Says Climate Change Is Real, but …",Atlantic,Robinson Meyer,2017-01-11,2017.0,1.0,NaN,"As chairman and CEO of ExxonMobil, Rex Tillers..."
73466,53288,The Biggest Intelligence Questions Raised by t...,Atlantic,Amy Zegart,2017-01-11,2017.0,1.0,NaN,I’ve spent nearly 20 years looking at intellig...
73467,53289,Trump Announces Plan That Does Little to Resol...,Atlantic,Jeremy Venook,2017-01-11,2017.0,1.0,NaN,Donald Trump will not be taking necessary st...
73468,53290,Dozens of For-Profit Colleges Could Soon Close,Atlantic,Emily DeRuy,2017-01-11,2017.0,1.0,NaN,Dozens of colleges could be forced to close ...
73469,53291,The Milky Way’s Stolen Stars,Atlantic,Marina Koren,2017-01-11,2017.0,1.0,NaN,The force of gravity can be described using a ...

In [9]:
file2 = pd.read_csv("articles2.csv")
file2

,Unnamed: 0,id,title,publication,author,date,year,month,url,content
0,53293,73471,Patriots Day Is Best When It Digs Past the Her...,Atlantic,David Sims,2017-01-11,2017.0,1.0,NaN,"Patriots Day, Peter Berg’s new thriller that r..."
1,53294,73472,A Break in the Search for the Origin of Comple...,Atlantic,Ed Yong,2017-01-11,2017.0,1.0,NaN,"In Norse mythology, humans and our world were ..."
2,53295,73474,Obama’s Ingenious Mention of Atticus Finch,Atlantic,Spencer Kornhaber,2017-01-11,2017.0,1.0,NaN,“If our democracy is to work in this increasin...
3,53296,73475,"Donald Trump Meets, and Assails, the Press",Atlantic,David A. Graham,2017-01-11,2017.0,1.0,NaN,Updated on January 11 at 5:05 p. m. In his fir...
4,53297,73476,Trump: ’I Think’ Hacking Was Russian,Atlantic,Kaveh Waddell,2017-01-11,2017.0,1.0,NaN,Updated at 12:25 p. m. After months of equivoc...
...,...,...,...,...,...,...,...,...,...,...
49994,103453,151902,"If Baltimore is serious about police reform, g...",Guardian,Lawrence Grandpre,2016-08-12,2016.0,8.0,https://www.theguardian.com/commentisfree/2016...,There have been many proposed solutions to the...
49995,103454,151903,The transition from summer to fall feels like ...,Guardian,Mary Valle,2016-08-28,2016.0,8.0,https://www.theguardian.com/commentisfree/2016...,"Maybe I feel like August won’t let go of me, b..."
49996,103455,151904,"Colombia: Farc’s female fighters, then and now...",Guardian,NaN,2016-09-16,2016.0,9.0,https://www.theguardian.com/artanddesign/2016/...,"Diana Marcela, 28, has spent 13 years with Far..."
49997,103456,151905,Why I’m optimistic about 2017,Guardian,Paul Mason,2016-12-26,2016.0,12.0,https://www.theguardian.com/politics/commentis...,"This Christmas break, for anybody steeped in t..."
49998,103457,151906,Prayer and pain: why gay conversion therapy is...,Guardian,Tom Dart,2016-07-15,2016.0,7.0,https://www.theguardian.com/world/2016/jul/15/...,Brian Nesbitt’s therapist made a suggestion in...

In [10]:
file3 = pd.read_csv("articles3.csv")
file3

,Unnamed: 0,id,title,publication,author,date,year,month,url,content
0,103459,151908,Alton Sterling’s son: ’Everyone needs to prote...,Guardian,Jessica Glenza,2016-07-13,2016.0,7.0,https://www.theguardian.com/us-news/2016/jul/1...,The son of a Louisiana man whose father was sh...
1,103460,151909,Shakespeare’s first four folios sell at auctio...,Guardian,NaN,2016-05-25,2016.0,5.0,https://www.theguardian.com/culture/2016/may/2...,Copies of William Shakespeare’s first four boo...
2,103461,151910,My grandmother’s death saved me from a life of...,Guardian,Robert Pendry,2016-10-31,2016.0,10.0,https://www.theguardian.com/commentisfree/2016...,"Debt: $20, 000, Source: College, credit cards,..."
3,103462,151911,I feared my life lacked meaning. Cancer pushed...,Guardian,Bradford Frost,2016-11-26,2016.0,11.0,https://www.theguardian.com/commentisfree/2016...,"It was late. I was drunk, nearing my 35th birt..."
4,103463,151912,Texas man serving life sentence innocent of do...,Guardian,NaN,2016-08-20,2016.0,8.0,https://www.theguardian.com/us-news/2016/aug/2...,A central Texas man serving a life sentence fo...
...,...,...,...,...,...,...,...,...,...,...
42566,146028,218078,An eavesdropping Uber driver saved his 16-year...,Washington Post,Avi Selk,2016-12-30,2016.0,12.0,https://web.archive.org/web/20161231004909/htt...,Uber driver Keith Avila picked up a p...
42567,146029,218079,Plane carrying six people returning from a Cav...,Washington Post,Sarah Larimer,2016-12-30,2016.0,12.0,https://web.archive.org/web/20161231004909/htt...,Crews on Friday continued to search L...
42568,146030,218080,After helping a fraction of homeowners expecte...,Washington Post,Renae Merle,2016-12-30,2016.0,12.0,https://web.archive.org/web/20161231004909/htt...,When the Obama administration announced a...
42569,146031,218081,"Yes, this is real: Michigan just banned bannin...",Washington Post,Chelsea Harvey,2016-12-30,2016.0,12.0,https://web.archive.org/web/20161231004909/htt...,This story has been updated. A new law in...
42570,146032,218082,What happened in Washington state after voters...,Washington Post,Christopher Ingraham,2016-12-29,2016.0,12.0,https://web.archive.org/web/20161231004909/htt...,The nation’s first recreational marijuana...

In [34]:
file4 = pd.read_csv("articles_data.csv", header=0)
file4

,Unnamed: 0,source_id,source_name,author,title,description,url,url_to_image,published_at,content,top_article,engagement_reaction_count,engagement_comment_count,engagement_share_count,engagement_comment_plugin_count
0,0,reuters,Reuters,Reuters Editorial,NTSB says Autopilot engaged in 2018 California...,The National Transportation Safety Board said ...,https://www.reuters.com/article/us-tesla-crash...,https://s4.reutersmedia.net/resources/r/?m=02&...,2019-09-03T16:22:20Z,WASHINGTON (Reuters) - The National Transporta...,0.0,0.0,0.0,2528.0,0.0
1,1,the-irish-times,The Irish Times,Eoin Burke-Kennedy,Unemployment falls to post-crash low of 5.2%,Latest monthly figures reflect continued growt...,https://www.irishtimes.com/business/economy/un...,https://www.irishtimes.com/image-creator/?id=1...,2019-09-03T10:32:28Z,The States jobless rate fell to 5.2 per cent l...,0.0,6.0,10.0,2.0,0.0
2,2,the-irish-times,The Irish Times,Deirdre McQuillan,"Louise Kennedy AW2019: Long coats, sparkling t...",Autumn-winter collection features designer’s g...,https://www.irishtimes.com/\t\t\t\t\t\t\t/life...,https://www.irishtimes.com/image-creator/?id=1...,2019-09-03T14:40:00Z,Louise Kennedy is showing off her autumn-winte...,1.0,NaN,NaN,NaN,NaN
3,3,al-jazeera-english,Al Jazeera English,Al Jazeera,North Korean footballer Han joins Italian gian...,Han is the first North Korean player in the Se...,https://www.aljazeera.com/news/2019/09/north-k...,https://www.aljazeera.com/mritems/Images/2019/...,2019-09-03T17:25:39Z,"Han Kwang Song, the first North Korean footbal...",0.0,0.0,0.0,7.0,0.0
4,4,bbc-news,BBC News,BBC News,UK government lawyer says proroguing parliamen...,"The UK government's lawyer, David Johnston arg...",https://www.bbc.co.uk/news/av/uk-scotland-4956...,https://ichef.bbci.co.uk/news/1024/branded_new...,2019-09-03T14:39:21Z,NaN,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10432,10432,abc-news,ABC News,The Associated Press,Drop in US service sector activity raises econ...,"Get breaking national and world news, broadcas...",https://abcnews.go.com/Business/wireStory/drop...,https://s.abcnews.com/images/US/WireAP_eb147c9...,2019-10-03T16:30:16Z,Growth in the U.S. economys vast services sect...,0.0,0.0,0.0,0.0,0.0
10433,10433,reuters,Reuters,Sumeet Chatterjee,Banker defections pose challenge for Credit Su...,The announcement by Julius Baer this week that...,https://www.reuters.com/article/us-credit-suis...,https://s3.reutersmedia.net/resources/r/?m=02&...,2019-10-03T15:59:52Z,ZURICH/HONG KONG (Reuters) - The announcement ...,0.0,0.0,0.0,627.0,0.0
10434,10434,cnn,CNN,"Lauren M. Johnson, CNN","A 5-year-old cancer survivor donates 3,000 toy...",Weston Newswanger is just a normal 5-year-old ...,https://www.cnn.com/2019/10/03/us/five-year-ol...,https://cdn.cnn.com/cnnnext/dam/assets/1910021...,2019-10-03T11:20:06Z,NaN,0.0,4072.0,179.0,466.0,0.0
10435,10435,cbs-news,CBS News,CBS News,Fateful Connection,A detective is haunted by the case of two wome...,https://www.cbsnews.com/video/fateful-connecti...,https://cbsnews1.cbsistatic.com/hub/i/r/2019/1...,2019-10-03T16:40:03Z,NaN,0.0,0.0,0.0,0.0,0.0
10436,10436,cbs-news,CBS News,CBS News,"Love, Hate & Obsession",Who wanted one-time millionaire Lanny Horwitz ...,https://www.cbsnews.com/video/love-hate-obsess...,https://cbsnews1.cbsistatic.com/hub/i/r/2017/0...,2019-10-03T16:35:13Z,NaN,0.0,0.0,0.0,0.0,0.0

In [12]:
file5 = pd.read_csv("bbc_news.csv")
file5

,title,pubDate,guid,link,description
0,Ukraine: Angry Zelensky vows to punish Russian...,"Mon, 07 Mar 2022 08:01:56 GMT",https://www.bbc.co.uk/news/world-europe-60638042,https://www.bbc.co.uk/news/world-europe-606380...,The Ukrainian president says the country will ...
1,War in Ukraine: Taking cover in a town under a...,"Sun, 06 Mar 2022 22:49:58 GMT",https://www.bbc.co.uk/news/world-europe-60641873,https://www.bbc.co.uk/news/world-europe-606418...,"Jeremy Bowen was on the frontline in Irpin, as..."
2,Ukraine war 'catastrophic for global food',"Mon, 07 Mar 2022 00:14:42 GMT",https://www.bbc.co.uk/news/business-60623941,https://www.bbc.co.uk/news/business-60623941?a...,One of the world's biggest fertiliser firms sa...
3,Manchester Arena bombing: Saffie Roussos's par...,"Mon, 07 Mar 2022 00:05:40 GMT",https://www.bbc.co.uk/news/uk-60579079,https://www.bbc.co.uk/news/uk-60579079?at_medi...,The parents of the Manchester Arena bombing's ...
4,Ukraine conflict: Oil price soars to highest l...,"Mon, 07 Mar 2022 08:15:53 GMT",https://www.bbc.co.uk/news/business-60642786,https://www.bbc.co.uk/news/business-60642786?a...,Consumers are feeling the impact of higher ene...
...,...,...,...,...,...
29751,Ratcliffe wants 'national stadium in north',"Wed, 21 Feb 2024 18:01:39 GMT",https://www.bbc.co.uk/sport/football/68361025,https://www.bbc.co.uk/sport/football/68361025,New Manchester United co-owner Sir Jim Ratclif...
29752,Stokes bowls in nets before fourth Test,"Wed, 21 Feb 2024 10:56:13 GMT",https://www.bbc.co.uk/sport/av/cricket/68358578,https://www.bbc.co.uk/sport/av/cricket/68358578,England captain Ben Stokes could bowl in the f...
29753,Gauff 'fuelled' by umpire row to reach Dubai q...,"Wed, 21 Feb 2024 19:54:21 GMT",https://www.bbc.co.uk/sport/tennis/68365096,https://www.bbc.co.uk/sport/tennis/68365096,US Open champion Coco Gauff says a long disagr...
29754,Verstappen makes ominous start to pre-season t...,"Wed, 21 Feb 2024 16:51:47 GMT",https://www.bbc.co.uk/sport/formula1/68362786,https://www.bbc.co.uk/sport/formula1/68362786,Red Bull's Max Verstappen makes an ominous sta...
29755,Osimhen scores on return as Napoli hold Barcelona,"Wed, 21 Feb 2024 22:03:23 GMT",https://www.bbc.co.uk/sport/football/68348509,https://www.bbc.co.uk/sport/football/68348509,Victor Osimhen scores in his first Napoli matc...

In [13]:
file1.isnull().sum()

Unnamed: 0         0
title              0
publication        0
author          6306
date               0
year               0
month              0
url            50000
content            0
dtype: int64

In [26]:
file1["author"].fillna('Sin autor', inplace=True)
file1["url"].fillna("Sin url", inplace=True)

file1.isnull().sum()

Unnamed: 0     0
title          0
publication    0
author         0
date           0
year           0
month          0
url            0
content        0
dtype: int64

In [27]:
file1

,Unnamed: 0,title,publication,author,date,year,month,url,content
id,,,,,,,,,
17283,0,House Republicans Fret About Winning Their Hea...,New York Times,Carl Hulse,2016-12-31,2016.0,12.0,Sin url,WASHINGTON — Congressional Republicans have...
17284,1,Rift Between Officers and Residents as Killing...,New York Times,Benjamin Mueller and Al Baker,2017-06-19,2017.0,6.0,Sin url,"After the bullet shells get counted, the blood..."
17285,2,"Tyrus Wong, ‘Bambi’ Artist Thwarted by Racial ...",New York Times,Margalit Fox,2017-01-06,2017.0,1.0,Sin url,"When Walt Disney’s “Bambi” opened in 1942, cri..."
17286,3,"Among Deaths in 2016, a Heavy Toll in Pop Musi...",New York Times,William McDonald,2017-04-10,2017.0,4.0,Sin url,"Death may be the great equalizer, but it isn’t..."
17287,4,Kim Jong-un Says North Korea Is Preparing to T...,New York Times,Choe Sang-Hun,2017-01-02,2017.0,1.0,Sin url,"SEOUL, South Korea — North Korea’s leader, ..."
...,...,...,...,...,...,...,...,...,...
73465,53287,"Rex Tillerson Says Climate Change Is Real, but …",Atlantic,Robinson Meyer,2017-01-11,2017.0,1.0,Sin url,"As chairman and CEO of ExxonMobil, Rex Tillers..."
73466,53288,The Biggest Intelligence Questions Raised by t...,Atlantic,Amy Zegart,2017-01-11,2017.0,1.0,Sin url,I’ve spent nearly 20 years looking at intellig...
73467,53289,Trump Announces Plan That Does Little to Resol...,Atlantic,Jeremy Venook,2017-01-11,2017.0,1.0,Sin url,Donald Trump will not be taking necessary st...
73468,53290,Dozens of For-Profit Colleges Could Soon Close,Atlantic,Emily DeRuy,2017-01-11,2017.0,1.0,Sin url,Dozens of colleges could be forced to close ...
73469,53291,The Milky Way’s Stolen Stars,Atlantic,Marina Koren,2017-01-11,2017.0,1.0,Sin url,The force of gravity can be described using a ...

In [15]:
file2.isnull().sum()

Unnamed: 0        0
id                0
title             1
publication       0
author         8598
date           2626
year           2626
month          2626
url            7011
content           0
dtype: int64

In [16]:
file2["title"].fillna("Sin titulo", inplace = True)
file2["author"].fillna("Sin autor", inplace = True)
file2["date"].fillna("Sin fecha", inplace = True)
file2["year"].fillna("Sin año", inplace = True)
file2["month"].fillna("Sin mes", inplace = True)
file2["url"].fillna("Sin enlace", inplace = True)

file2.isnull().sum()

C:\Users\samcu\AppData\Local\Temp\ipykernel_19268\1629204662.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Sin año' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  file2["year"].fillna("Sin año", inplace = True)
C:\Users\samcu\AppData\Local\Temp\ipykernel_19268\1629204662.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Sin mes' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  file2["month"].fillna("Sin mes", inplace = True)

Unnamed: 0     0
id             0
title          0
publication    0
author         0
date           0
year           0
month          0
url            0
content        0
dtype: int64

In [24]:
file2

,Unnamed: 0,id,title,publication,author,date,year,month,url,content
0,53293,73471,Patriots Day Is Best When It Digs Past the Her...,Atlantic,David Sims,2017-01-11,2017.0,1.0,Sin enlace,"Patriots Day, Peter Berg’s new thriller that r..."
1,53294,73472,A Break in the Search for the Origin of Comple...,Atlantic,Ed Yong,2017-01-11,2017.0,1.0,Sin enlace,"In Norse mythology, humans and our world were ..."
2,53295,73474,Obama’s Ingenious Mention of Atticus Finch,Atlantic,Spencer Kornhaber,2017-01-11,2017.0,1.0,Sin enlace,“If our democracy is to work in this increasin...
3,53296,73475,"Donald Trump Meets, and Assails, the Press",Atlantic,David A. Graham,2017-01-11,2017.0,1.0,Sin enlace,Updated on January 11 at 5:05 p. m. In his fir...
4,53297,73476,Trump: ’I Think’ Hacking Was Russian,Atlantic,Kaveh Waddell,2017-01-11,2017.0,1.0,Sin enlace,Updated at 12:25 p. m. After months of equivoc...
...,...,...,...,...,...,...,...,...,...,...
49994,103453,151902,"If Baltimore is serious about police reform, g...",Guardian,Lawrence Grandpre,2016-08-12,2016.0,8.0,https://www.theguardian.com/commentisfree/2016...,There have been many proposed solutions to the...
49995,103454,151903,The transition from summer to fall feels like ...,Guardian,Mary Valle,2016-08-28,2016.0,8.0,https://www.theguardian.com/commentisfree/2016...,"Maybe I feel like August won’t let go of me, b..."
49996,103455,151904,"Colombia: Farc’s female fighters, then and now...",Guardian,Sin autor,2016-09-16,2016.0,9.0,https://www.theguardian.com/artanddesign/2016/...,"Diana Marcela, 28, has spent 13 years with Far..."
49997,103456,151905,Why I’m optimistic about 2017,Guardian,Paul Mason,2016-12-26,2016.0,12.0,https://www.theguardian.com/politics/commentis...,"This Christmas break, for anybody steeped in t..."
49998,103457,151906,Prayer and pain: why gay conversion therapy is...,Guardian,Tom Dart,2016-07-15,2016.0,7.0,https://www.theguardian.com/world/2016/jul/15/...,Brian Nesbitt’s therapist made a suggestion in...

In [17]:
file3.isnull().sum()

Unnamed: 0       0
id               0
title            1
publication      0
author         972
date            15
year            15
month           15
url              0
content          0
dtype: int64

In [22]:
file3["title"].fillna("Sin titulo", inplace = True)
file3["author"].fillna("Sin autor", inplace = True)
file3["date"].fillna("Sin fecha", inplace = True)
file3["year"].fillna("Sin año", inplace = True)
file3["month"].fillna("Sin mes", inplace = True)
file3["url"].fillna("Sin enlace", inplace = True)

file3.isnull().sum()

Unnamed: 0     0
id             0
title          0
publication    0
author         0
date           0
year           0
month          0
url            0
content        0
dtype: int64

In [23]:
file3

,Unnamed: 0,id,title,publication,author,date,year,month,url,content
0,103459,151908,Alton Sterling’s son: ’Everyone needs to prote...,Guardian,Jessica Glenza,2016-07-13,2016.0,7.0,https://www.theguardian.com/us-news/2016/jul/1...,The son of a Louisiana man whose father was sh...
1,103460,151909,Shakespeare’s first four folios sell at auctio...,Guardian,Sin autor,2016-05-25,2016.0,5.0,https://www.theguardian.com/culture/2016/may/2...,Copies of William Shakespeare’s first four boo...
2,103461,151910,My grandmother’s death saved me from a life of...,Guardian,Robert Pendry,2016-10-31,2016.0,10.0,https://www.theguardian.com/commentisfree/2016...,"Debt: $20, 000, Source: College, credit cards,..."
3,103462,151911,I feared my life lacked meaning. Cancer pushed...,Guardian,Bradford Frost,2016-11-26,2016.0,11.0,https://www.theguardian.com/commentisfree/2016...,"It was late. I was drunk, nearing my 35th birt..."
4,103463,151912,Texas man serving life sentence innocent of do...,Guardian,Sin autor,2016-08-20,2016.0,8.0,https://www.theguardian.com/us-news/2016/aug/2...,A central Texas man serving a life sentence fo...
...,...,...,...,...,...,...,...,...,...,...
42566,146028,218078,An eavesdropping Uber driver saved his 16-year...,Washington Post,Avi Selk,2016-12-30,2016.0,12.0,https://web.archive.org/web/20161231004909/htt...,Uber driver Keith Avila picked up a p...
42567,146029,218079,Plane carrying six people returning from a Cav...,Washington Post,Sarah Larimer,2016-12-30,2016.0,12.0,https://web.archive.org/web/20161231004909/htt...,Crews on Friday continued to search L...
42568,146030,218080,After helping a fraction of homeowners expecte...,Washington Post,Renae Merle,2016-12-30,2016.0,12.0,https://web.archive.org/web/20161231004909/htt...,When the Obama administration announced a...
42569,146031,218081,"Yes, this is real: Michigan just banned bannin...",Washington Post,Chelsea Harvey,2016-12-30,2016.0,12.0,https://web.archive.org/web/20161231004909/htt...,This story has been updated. A new law in...
42570,146032,218082,What happened in Washington state after voters...,Washington Post,Christopher Ingraham,2016-12-29,2016.0,12.0,https://web.archive.org/web/20161231004909/htt...,The nation’s first recreational marijuana...

In [35]:
file4.isnull().sum()

Unnamed: 0                            0
source_id                             0
source_name                           0
author                             1020
title                                 2
description                          24
url                                   1
url_to_image                        656
published_at                          1
content                            1292
top_article                           2
engagement_reaction_count           118
engagement_comment_count            118
engagement_share_count              118
engagement_comment_plugin_count     118
dtype: int64

In [37]:
columnas = ['engagement_reaction_count', 'engagement_comment_count', 'engagement_share_count', 'engagement_comment_plugin_count']
file4 = file4.drop(columns=columnas)
file4.isnull().sum()

Unnamed: 0         0
source_id          0
source_name        0
author          1020
title              2
description       24
url                1
url_to_image     656
published_at       1
content         1292
top_article        2
dtype: int64

In [39]:
file4['author'].fillna('Sin autor', inplace=True)
file4['title'].fillna('Sin titulo', inplace=True)
file4['description'].fillna('Sin descripcion', inplace=True)
file4['url'].fillna('Sin url', inplace=True)
file4['url_to_image'].fillna('Sin enlace de imagen', inplace=True)
file4['published_at'].fillna('Sin fecha', inplace=True)
file4['content'].fillna('Sin contenido disponible', inplace=True)
file4['top_article'].fillna('Sin información', inplace=True)

file4.isnull().sum()

C:\Users\samcu\AppData\Local\Temp\ipykernel_19268\1553305007.py:8: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Sin información' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  file4['top_article'].fillna('Sin información', inplace=True)

Unnamed: 0      0
source_id       0
source_name     0
author          0
title           0
description     0
url             0
url_to_image    0
published_at    0
content         0
top_article     0
dtype: int64

In [40]:
file4

,Unnamed: 0,source_id,source_name,author,title,description,url,url_to_image,published_at,content,top_article
0,0,reuters,Reuters,Reuters Editorial,NTSB says Autopilot engaged in 2018 California...,The National Transportation Safety Board said ...,https://www.reuters.com/article/us-tesla-crash...,https://s4.reutersmedia.net/resources/r/?m=02&...,2019-09-03T16:22:20Z,WASHINGTON (Reuters) - The National Transporta...,0.0
1,1,the-irish-times,The Irish Times,Eoin Burke-Kennedy,Unemployment falls to post-crash low of 5.2%,Latest monthly figures reflect continued growt...,https://www.irishtimes.com/business/economy/un...,https://www.irishtimes.com/image-creator/?id=1...,2019-09-03T10:32:28Z,The States jobless rate fell to 5.2 per cent l...,0.0
2,2,the-irish-times,The Irish Times,Deirdre McQuillan,"Louise Kennedy AW2019: Long coats, sparkling t...",Autumn-winter collection features designer’s g...,https://www.irishtimes.com/\t\t\t\t\t\t\t/life...,https://www.irishtimes.com/image-creator/?id=1...,2019-09-03T14:40:00Z,Louise Kennedy is showing off her autumn-winte...,1.0
3,3,al-jazeera-english,Al Jazeera English,Al Jazeera,North Korean footballer Han joins Italian gian...,Han is the first North Korean player in the Se...,https://www.aljazeera.com/news/2019/09/north-k...,https://www.aljazeera.com/mritems/Images/2019/...,2019-09-03T17:25:39Z,"Han Kwang Song, the first North Korean footbal...",0.0
4,4,bbc-news,BBC News,BBC News,UK government lawyer says proroguing parliamen...,"The UK government's lawyer, David Johnston arg...",https://www.bbc.co.uk/news/av/uk-scotland-4956...,https://ichef.bbci.co.uk/news/1024/branded_new...,2019-09-03T14:39:21Z,Sin contenido disponible,0.0
...,...,...,...,...,...,...,...,...,...,...,...
10432,10432,abc-news,ABC News,The Associated Press,Drop in US service sector activity raises econ...,"Get breaking national and world news, broadcas...",https://abcnews.go.com/Business/wireStory/drop...,https://s.abcnews.com/images/US/WireAP_eb147c9...,2019-10-03T16:30:16Z,Growth in the U.S. economys vast services sect...,0.0
10433,10433,reuters,Reuters,Sumeet Chatterjee,Banker defections pose challenge for Credit Su...,The announcement by Julius Baer this week that...,https://www.reuters.com/article/us-credit-suis...,https://s3.reutersmedia.net/resources/r/?m=02&...,2019-10-03T15:59:52Z,ZURICH/HONG KONG (Reuters) - The announcement ...,0.0
10434,10434,cnn,CNN,"Lauren M. Johnson, CNN","A 5-year-old cancer survivor donates 3,000 toy...",Weston Newswanger is just a normal 5-year-old ...,https://www.cnn.com/2019/10/03/us/five-year-ol...,https://cdn.cnn.com/cnnnext/dam/assets/1910021...,2019-10-03T11:20:06Z,Sin contenido disponible,0.0
10435,10435,cbs-news,CBS News,CBS News,Fateful Connection,A detective is haunted by the case of two wome...,https://www.cbsnews.com/video/fateful-connecti...,https://cbsnews1.cbsistatic.com/hub/i/r/2019/1...,2019-10-03T16:40:03Z,Sin contenido disponible,0.0
10436,10436,cbs-news,CBS News,CBS News,"Love, Hate & Obsession",Who wanted one-time millionaire Lanny Horwitz ...,https://www.cbsnews.com/video/love-hate-obsess...,https://cbsnews1.cbsistatic.com/hub/i/r/2017/0...,2019-10-03T16:35:13Z,Sin contenido disponible,0.0

In [41]:
file5.isnull().sum()

title          0
pubDate        0
guid           0
link           0
description    0
dtype: int64

In [42]:
file5

,title,pubDate,guid,link,description
0,Ukraine: Angry Zelensky vows to punish Russian...,"Mon, 07 Mar 2022 08:01:56 GMT",https://www.bbc.co.uk/news/world-europe-60638042,https://www.bbc.co.uk/news/world-europe-606380...,The Ukrainian president says the country will ...
1,War in Ukraine: Taking cover in a town under a...,"Sun, 06 Mar 2022 22:49:58 GMT",https://www.bbc.co.uk/news/world-europe-60641873,https://www.bbc.co.uk/news/world-europe-606418...,"Jeremy Bowen was on the frontline in Irpin, as..."
2,Ukraine war 'catastrophic for global food',"Mon, 07 Mar 2022 00:14:42 GMT",https://www.bbc.co.uk/news/business-60623941,https://www.bbc.co.uk/news/business-60623941?a...,One of the world's biggest fertiliser firms sa...
3,Manchester Arena bombing: Saffie Roussos's par...,"Mon, 07 Mar 2022 00:05:40 GMT",https://www.bbc.co.uk/news/uk-60579079,https://www.bbc.co.uk/news/uk-60579079?at_medi...,The parents of the Manchester Arena bombing's ...
4,Ukraine conflict: Oil price soars to highest l...,"Mon, 07 Mar 2022 08:15:53 GMT",https://www.bbc.co.uk/news/business-60642786,https://www.bbc.co.uk/news/business-60642786?a...,Consumers are feeling the impact of higher ene...
...,...,...,...,...,...
29751,Ratcliffe wants 'national stadium in north',"Wed, 21 Feb 2024 18:01:39 GMT",https://www.bbc.co.uk/sport/football/68361025,https://www.bbc.co.uk/sport/football/68361025,New Manchester United co-owner Sir Jim Ratclif...
29752,Stokes bowls in nets before fourth Test,"Wed, 21 Feb 2024 10:56:13 GMT",https://www.bbc.co.uk/sport/av/cricket/68358578,https://www.bbc.co.uk/sport/av/cricket/68358578,England captain Ben Stokes could bowl in the f...
29753,Gauff 'fuelled' by umpire row to reach Dubai q...,"Wed, 21 Feb 2024 19:54:21 GMT",https://www.bbc.co.uk/sport/tennis/68365096,https://www.bbc.co.uk/sport/tennis/68365096,US Open champion Coco Gauff says a long disagr...
29754,Verstappen makes ominous start to pre-season t...,"Wed, 21 Feb 2024 16:51:47 GMT",https://www.bbc.co.uk/sport/formula1/68362786,https://www.bbc.co.uk/sport/formula1/68362786,Red Bull's Max Verstappen makes an ominous sta...
29755,Osimhen scores on return as Napoli hold Barcelona,"Wed, 21 Feb 2024 22:03:23 GMT",https://www.bbc.co.uk/sport/football/68348509,https://www.bbc.co.uk/sport/football/68348509,Victor Osimhen scores in his first Napoli matc...

In [43]:
archivos = [file1, file2, file3, file4,file5]
fileJoin = pd.concat(archivos, ignore_index=True)

fileJoin

,Unnamed: 0,title,publication,author,date,year,month,url,content,id,source_id,source_name,description,url_to_image,published_at,top_article,pubDate,guid,link
0,0.0,House Republicans Fret About Winning Their Hea...,New York Times,Carl Hulse,2016-12-31,2016.0,12.0,Sin url,WASHINGTON — Congressional Republicans have...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,Rift Between Officers and Residents as Killing...,New York Times,Benjamin Mueller and Al Baker,2017-06-19,2017.0,6.0,Sin url,"After the bullet shells get counted, the blood...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.0,"Tyrus Wong, ‘Bambi’ Artist Thwarted by Racial ...",New York Times,Margalit Fox,2017-01-06,2017.0,1.0,Sin url,"When Walt Disney’s “Bambi” opened in 1942, cri...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3.0,"Among Deaths in 2016, a Heavy Toll in Pop Musi...",New York Times,William McDonald,2017-04-10,2017.0,4.0,Sin url,"Death may be the great equalizer, but it isn’t...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4.0,Kim Jong-un Says North Korea Is Preparing to T...,New York Times,Choe Sang-Hun,2017-01-02,2017.0,1.0,Sin url,"SEOUL, South Korea — North Korea’s leader, ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182758,NaN,Ratcliffe wants 'national stadium in north',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,New Manchester United co-owner Sir Jim Ratclif...,NaN,NaN,NaN,"Wed, 21 Feb 2024 18:01:39 GMT",https://www.bbc.co.uk/sport/football/68361025,https://www.bbc.co.uk/sport/football/68361025
182759,NaN,Stokes bowls in nets before fourth Test,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,England captain Ben Stokes could bowl in the f...,NaN,NaN,NaN,"Wed, 21 Feb 2024 10:56:13 GMT",https://www.bbc.co.uk/sport/av/cricket/68358578,https://www.bbc.co.uk/sport/av/cricket/68358578
182760,NaN,Gauff 'fuelled' by umpire row to reach Dubai q...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,US Open champion Coco Gauff says a long disagr...,NaN,NaN,NaN,"Wed, 21 Feb 2024 19:54:21 GMT",https://www.bbc.co.uk/sport/tennis/68365096,https://www.bbc.co.uk/sport/tennis/68365096
182761,NaN,Verstappen makes ominous start to pre-season t...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Red Bull's Max Verstappen makes an ominous sta...,NaN,NaN,NaN,"Wed, 21 Feb 2024 16:51:47 GMT",https://www.bbc.co.uk/sport/formula1/68362786,https://www.bbc.co.uk/sport/formula1/68362786
182762,NaN,Osimhen scores on return as Napoli hold Barcelona,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Victor Osimhen scores in his first Napoli matc...,NaN,NaN,NaN,"Wed, 21 Feb 2024 22:03:23 GMT",https://www.bbc.co.uk/sport/football/68348509,https://www.bbc.co.uk/sport/football/68348509

In [44]:
fileJoin.isnull().sum()

Unnamed: 0       29756
title                0
publication      40193
author           29756
date             40193
year             40193
month            40193
url              29756
content          29756
id               90193
source_id       172326
source_name     172326
description     142570
url_to_image    172326
published_at    172326
top_article     172326
pubDate         153007
guid            153007
link            153007
dtype: int64

In [45]:
fileJoin.dtypes

Unnamed: 0      float64
title            object
publication      object
author           object
date             object
year             object
month            object
url              object
content          object
id              float64
source_id        object
source_name      object
description      object
url_to_image     object
published_at     object
top_article      object
pubDate          object
guid             object
link             object
dtype: object

In [46]:
fileJoin.to_csv('noticiasUnificado.csv', index=False)